base_url = "https://250kb.club/"
title = "The 250kb Club"
description = "An exclusive membership for web pages presenting themselves in no more than 250kb."
default_language = "en"

compile_sass = false
build_search_index = false
minify_html = true
generate_feeds = true
feed_filenames = ["rss.xml"]
hard_link_static = true
taxonomies = []
generate_sitemap = true
generate_robots_txt = true

author = "koehr"

[link_checker]
skip_prefixes = []
skip_anchor_prefixes = []
internal_level = "error"
external_level = "error"

[markdown]
highlight_code = false
render_emoji = false
external_links_target_blank = true
external_links_no_follow = true
external_links_no_referrer = false
smart_punctuation = true
lazy_async_image = true
bottom_footnotes = false

[search]
index_format = "fuse_javascript"
include_title = false
include_description = false
include_path = false
include_content = false

[extra]
author_homepage = "https://koehr.ing"
